api/urls.py
from .views import *                                
from django.urls import path, include
# from django.views.decorators.cache import cache_page
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'products', ProductsViewSet)
router.register(r'basket', BasketViewSet)

app_name= 'api'
urlpatterns = [
    path('', include(router.urls)),
    path('', include(router.urls)),
]

main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from products.views import *
from django.conf.urls.static import static
from orders.views import stripe_webhook_view
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('user/', include('user.urls', namespace='user')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', views.obtain_auth_token)
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from .views import *                                
from django.urls import path


app_name= 'orders'

urlpatterns = [
    path('order_create/', OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('order_success/', SuccessOrderView.as_view(), name='order_success'),
    path('order_cancel/', CanceledOrderView.as_view(), name='order_cancel'),
    path('', OrderListView.as_view(), name='order_list'),
]

orders/models.py
from django.db import models
from products.models import Basket
from user.models import User                                                                                                    

class Order(models.Model):
    CREATED = 0
    PAID = 1
    ON_WAY = 2 
    DELIVERED = 3
    STATUSES = ((CREATED, 'Создан'),
                (PAID, 'Оплачен'),
                (ON_WAY, 'В пути'),
                (DELIVERED, 'Доставлен')
                 )
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)
    email = models.EmailField(max_length=256)
    address = models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)
     
    def __str__(self):
         return f'Order #{self.id}. {self.first_name} {self.last_name}'
         

    def update_after_payment(self):
        basket = Basket.objects.filter(user=self.initiator)
        self.status = self.PAID
        self.basket_history = {
            'purchased_items': [item.de_json() for item in basket],
            'total_sum': float(basket.total_sum())
        }
        basket.delete()
        self.save()

    def get_status_diplay(self):
        stat_dict = {0: 'Создан', 1:'Оплачен', 2: 'В пути', 3: 'Доставлен'}
        return stat_dict[self.status]
     

orders/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
                                  attrs={'class': "form-control",
                                         'placeholder': "Иван"})) 	  
    last_name = forms.CharField(widget=forms.TextInput(
                                  attrs={'class': "form-control",
                                         'placeholder': "Иванов"})) 	
    email = forms.EmailField(widget=forms.EmailInput(
                                  attrs={'class': "form-control",
                                         'placeholder': "you@example.com"}))
    address = forms.CharField(widget=forms.TextInput(
                attrs={'class': "form-control",
                        'placeholder': "Россия, Москва, ул. Мира, дом 6"}))  


    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address']

orders/views.py
from http import HTTPStatus
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView
from .forms import OrderForm
from common.utils import TitleMixin
import stripe
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from products.models import Basket
from orders.models import *
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

stripe.api_key = settings.STRIPE_SECRET_KEY 


class SuccessOrderView(TitleMixin, TemplateView):
    template_name = "orders/success.html"
    title = 'Store - Спасибо за заказ!'


class CanceledOrderView(TemplateView):
    template_name = "orders/cancel.html"


class OrderListView(TitleMixin, ListView):
    '''queryset = Order.objects.all() прописать обязательно'''
    template_name = "orders/orders.html"
    title = 'Store - Заказы'
    queryset = Order.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(initiator=self.request.user)
    

class OrderDetailView(DetailView):
    '''Отобразит автоматически из БД по pk  необходимый заказ'''
    model = Order
    template_name = "orders/order.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Обязательно в этом классе object, без s
        context["title"] = f'Store - Заказ # {self.object.id}'
        return context
    


class OrderCreateView(TitleMixin, CreateView):
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:order_create')
    title = 'Store - Оформление заказа'

    def post(self, request, *args: str, **kwargs):
        '''Попробовать вынести логику корзины из контроллера'''
        basket = Basket.objects.filter(user=self.request.user)

        line_items = []
        for item in basket:
            unit = {
                'price': item.product.strip_id,
                'quantity': item.quantity,
            }
            line_items.append(unit)
        super().post(request, *args, **kwargs)
        checkout_session = stripe.checkout.Session.create(
        line_items= line_items,
        # Важное добавление.. object это как instance .. объект в которым работаем
        metadata = {'order_id': self.object.id},
        mode='payment',
        success_url='{}{}'.format(settings.DOMAIN_NAME,
                    reverse('orders:order_success')),
        cancel_url='{}{}'.format(settings.DOMAIN_NAME,
                    reverse('orders:order_cancel')),
        )

        return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)


    def form_valid(self, form):
        '''При валидации добавляем еще одно обязательное поле initiator'''
        ''' instance -  это мы берем из формы сам объект, без этого не работает'''
        form.instance.initiator = self.request.user
        return super().form_valid(form)


@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
        payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
    # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
    # Invalid signature
        return HttpResponse(status=400)

  # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        session = stripe.checkout.Session.retrieve(
        event['data']['object']['id'],
        expand=['line_items'],
        )       

    # line_items = session.line_items
    # Fulfill the purchase...
        fulfill_order(session)

  # Passed signature verification
    return HttpResponse(status=200)

def fulfill_order(session):
    order_id = int(session.metadata.order_id)
    order = Order.objects.get(id=order_id)
    order.update_after_payment()

orders/templates/orders/cancel.html
<!DOCTYPE html>
<html>
<head>
  <title>Checkout canceled</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
</body>
</html>

orders/templates/orders/order-create.html
{% extends 'products/base.html' %}
{% load humanize %}

{% block content %}
<!-- Page Content -->
<section>
    <div class="alert alert-warning text-center" role="alert">
        Пожалуйста, заполните адрес электронной почты.
    </div>
    <div class="container">
        <div class="py-5 text-center">
            <h1>Оформление заказа</h1>
        </div>
        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Корзина</span>
                    <span class="badge badge-primary badge-pill text-white">{{ basket.total_quantity }}</span>
                </h4>
                {% for item in basket        %}
                <ul class="list-group mb-3">
                    <li class="list-group-item d-flex justify-content-between lh-sm">
                        <div>
                            <h6 class="my-0">{{ item.product.name }}</h6>
                            <small class="text-muted">{{ item.quantity }} шт.</small>
                        </div>
                        <span class="text-muted">{{ item.sum|intcomma }} руб.</span>
                    </li>               
                    {% endfor %}
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Сумма к оплате</span>
                        <strong>{{ basket.total_sum|intcomma }} руб.</strong>
                    </li>
                </ul>
            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3">Адрес доставки</h4>
                <form action={% url 'orders:order_create' %} method='post'>
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label for={{ form.first_name.id_for_label }} class="form-label">Имя</label>
                            {{ form.first_name }}
                        </div>

                        <div class="col-sm-6">
                            <label for={{ form.last_name.id_for_label }} class="form-label">Фамилия</label>
                            {{ form.last_name }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for={{ form.emal.id_for_label }} class="form-label">Адрес электронной почты</label>
                            {{ form.email }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for={{ form.address.id_for_label }} class="form-label">Адрес</label>
                        {{ form.address }}
                        </div>

                    </div>

                    <hr class="my-4">

                    <button class="w-100 btn btn-primary btn-lg" type="submit">Продолжить</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

orders/templates/orders/order.html
{% extends 'products/base.html' %}
{% load humanize %}

{% block content %}
<!-- Page Content -->
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Заказ № {{ object.id }}</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Название</th>
                        <th scope="col">Кол-во</th>
                        <th scope="col">Цена</th>
                        <th scope="col">Сумма</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item  in object.basket_history.purchased_items %}
                    <tr>
                        <th scope="row">
                            {{ item.product_name }}
                        </th>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.price|intcomma }} руб.</td>
                        <td>{{ item.sum|intcomma }} руб.</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <p class="float-right h4 mt-3">Итого: {{ object.basket_history.total_sum|intcomma }} руб.</p>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

orders/templates/orders/orders.html
{% extends 'products/base.html' %}
{% load humanize %}


{% block content %}
<!-- Page Content -->
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Заказы</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr class="table-light">
                        <th scope="col">Номер заказа</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Создан</th>
                        <th scope="col">Итого</th>
                        <th scope="col">Действие</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in object_list %}
                        <tr>
                            <th scope="row">{{ order.id }}</th>
                            <td>{{ order.get_status_diplay }}</td>
                            <td>{{ order.created|naturaltime }}</td>
                            <td>{{order.basket_history.total_sum|intcomma }} руб.</td>
                            <td>
                                <a href={% url 'orders:order_detail' order.id %}>просмотреть</a>
                            </td>
                        </tr>
                    {% endfor %}
                    {% comment %} <tr class="table-success">
                        <th scope="row">2</th>
                        <td>Досталвен</td>
                        <td>16 июля 21 года</td>
                        <td>4 876 руб.</td>
                        <td>
                            <a href="order.html">просмотреть</a>
                        </td>
                    </tr>
                    <tr class="table-info">
                        <th scope="row">3</th>
                        <td>В пути</td>
                        <td>14 нояб. 21 года</td>
                        <td>9 566 руб.</td>
                        <td>
                            <a href="order.html">просмотреть</a>
                        </td>
                    </tr> {% endcomment %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

orders/templates/orders/success.html
{% extends 'user/base.html' %}

{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header">
                        <h3 class="text-center font-weight-light my-4">Спасибо за заказ!</h3>
                    </div>
                    <div class="card-body text-center">
                        <h4>
                            Ваш заказ успешно сформирован.
                        </h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}
     