api/urls.py
from .views import *                                
from django.urls import path, include
# from django.views.decorators.cache import cache_page
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'products', ProductsViewSet)
router.register(r'basket', BasketViewSet)

app_name= 'api'
urlpatterns = [
    path('', include(router.urls)),
    path('', include(router.urls)),
]

main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from products.views import *
from django.conf.urls.static import static
from orders.views import stripe_webhook_view
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('user/', include('user.urls', namespace='user')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', views.obtain_auth_token)
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from .views import *                                
from django.urls import path


app_name= 'orders'

urlpatterns = [
    path('order_create/', OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('order_success/', SuccessOrderView.as_view(), name='order_success'),
    path('order_cancel/', CanceledOrderView.as_view(), name='order_cancel'),
    path('', OrderListView.as_view(), name='order_list'),
]

products/urls.py
from .views import *                                
from django.urls import path
# from django.views.decorators.cache import cache_page

app_name= 'products'
urlpatterns = [
    # path('', cache_page(15)(ProductsListView.as_view()), name='index'),
    path('', ProductsListView.as_view(), name='index'),
    # контроллер будет тот же, просто в него добавим условие проверки
    path('category/<int:category_id>', ProductsListView.as_view(), name='category'),
    # #
    path('page/<int:page>', ProductsListView.as_view(), name='paginator'),
    # int прописывается так же как и в контроллеле параметр функции и в шаблоне его передаем 
    path('basket/add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required

app_name = 'user'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserCreateView.as_view(), name='register'),
    # UpdateView должен получить в маршруте pk пользователя с которым работает!!! 
    path('profile/<int:pk>', ProfileUpdateView.as_view(), name='profile'),
    path('logout/', logout, name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.urls import reverse
from django.conf import settings
from django.utils.timezone import now
from django.template.loader import get_template
# from django.shortcuts import render

class User(AbstractUser):             
    '''При переопределении в настройках нужно прописать это обязательно'''
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    is_verified_email = models.BooleanField(default=False)


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True) # Уникальный id для пользователя
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()  # срок годности ссылки для верификации

    def __str__(self) -> str:
        return f'EmailVerification for {self.user.email}'

    def send_verification_email(self):
        link = reverse('user:email_verification', kwargs={'email': self.user.email,
                                                          'code': self.code})
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Подтверждение учетной записи для {self.user.username}'
        # message = "Для подтвердждения учетной записи для {} перейдите по ссылке {}".format(
        #     self.user.username,
        #     verification_link
        # )
        
        send_mail(
        subject=subject, message='',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[self.user.email],
        fail_silently=False,
        html_message=get_template('emails/email_verify.html')
        .render({'link': verification_link, 'username': self.user.username})
        )

    def is_expired(self):
        return True if now() >= self.expiration else False

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.forms import ValidationError
# from django.contrib.auth.models import User
# from django.core.exceptions import ValidationError
# from captcha.fields import CaptchaField
from .models import *
from django.utils.timezone import now
import uuid
from datetime import timedelta
from .tasks import *

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control py-4",
                              'placeholder': "Введите имя пользователя"})) 		
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': "form-control py-4",
                              'placeholder': "Введите пароль"}))	

    class Meta:
        model = User  # Указывается с какой моделью связь
        fields = ['username', 'password']  # Поля с которыми будем работать


class UserRegisterForm(UserCreationForm): 
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control py-4",
                              'placeholder': "Введите имя"})) 	  
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control py-4",
                              'placeholder': "Введите фамилию"})) 	
    username = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control py-4",
                              'placeholder': "Введите логин"})) 	      
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': "form-control py-4",
                              'placeholder': "Введите электронную почту"})) 	                
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': "form-control py-4",
                              'placeholder': "Введите пароль"})) 			
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': "form-control py-4",
                              'placeholder': "Введите подтверждение пароля"})) 	

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')  # Поля с коротымы работаем

    def save(self, commit=True):
        '''Переопределяем функцию сохранения при регистрации, добавляем новые операции'''
        user = super().save(commit)
        send_email_verification.delay(user.id)
        # expiration = now() + timedelta(hours=48)
        # record = EmailVerification.objects.create(code=uuid.uuid4(),user=user, expiration=expiration)
        # record.send_verification_email()
        return user

    def clean_email(self):   
        '''Кастомная валидация дубликатов почты'''
        email = self.cleaned_data['email']
        if User.objects.filter(email=email):
            raise ValidationError('Такой адрес электронной почты уже зарегистрирован')
        return email


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control py-4"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control py-4"}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': "custom-file-input"}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control py-4", 'readonly': True}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': "form-control py-4", 'readonly': True}))
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'image', 'username', 'email']

user/views.py
from products.models import Basket
from django.urls import reverse_lazy
from django.shortcuts import render, redirect  # HttpResponseRedirect
from .forms import *
from django.contrib import auth, messages
from django.db.models import *
# from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from common.utils import TitleMixin
from django.views.generic.base import TemplateView

class UserLoginView(TitleMixin, LoginView):
    # model =  стоит по автомату User
    template_name = 'user/login.html'
    form_class = UserLoginForm
    title = 'Store - Авторизация'
    
 
    # def get_success_url(self):
    #     '''Но можно в настройка прописать LOGIN_REDIRECT_URL = "/" '''
    #     return reverse_lazy('index')

# def login(request):    # Потренироваться переписать все это через классы, тут слишком много логики
#     if request.method == 'POST':
#         form = UserLoginForm(data=request.POST)
#         if form.is_valid():
#             username = request.POST['username']
#             password = request.POST['password']
#             user = auth.authenticate(username=username, password=password)
#             if user:
#                 auth.login(request, user)
#                 return redirect('index')      # Можно слелать просто редирект а не усложнять  HttpResponseRedirect(reverse)
#     else:
#         form = UserLoginForm()

#     context = {
#         'form': form,
#     }
#     return render(request, 'user/login.html', context)


class UserCreateView(TitleMixin, SuccessMessageMixin, CreateView):
    title = 'Store - Регистрация'
    model = User
    form_class = UserRegisterForm
    template_name = "user/register.html"
    success_url = reverse_lazy('user:login')
    success_message = 'Регистрация прошла успешно!'
    


# def register(request):
#     if request.method == 'POST':
#         form = UserRegisterForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Регистрация прошла успешно!')
#             return redirect('user:login')
#     else:
#         form = UserRegisterForm()
#     context = {
#         'form': form
#     }
#     return render(request, 'user/register.html', context)

class ProfileUpdateView(TitleMixin, LoginRequiredMixin, UpdateView):
    '''Добавлен спец миксик, первым в очереди'''
    model = User
    form_class = UserProfileForm
    template_name = "user/profile.html"
    title = 'Store - Личный кабинет'
    
    # Закоментим тк сделали контекст процессор
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     # self Содержит в себе еще и request, можно  еще self.object
    #     context['basket'] = Basket.objects.filter(user=self.request.user)
    #     return context

    def get_success_url(self) -> str:
        '''Это для того чтобы передать тот самый id  в маршрут иначе можно просто success_url'''
        return reverse_lazy('user:profile', args=(self.object.id,)) # Кортеж


# @login_required()
# def profile(request):
#     if request.method == 'POST':
#         form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('user:profile')
#     else:
#         form = UserProfileForm(instance=request.user) 

#     basket = Basket.objects.filter(user=request.user)
#     # Ниже решение в лоб простого суммирования
#     # total_sum = sum(item.sum() for item in basket)
#     # total_quantity = sum(item.quantity for item in basket)

#     context = {
#         'title': 'Store - profile',
#         'form': form,
#         'basket': Basket.objects.filter(user=request.user),
#         # 'total_quantity': total_quantity,
#         # 'total_sum': total_sum,
#     }
#     return render(request, 'user/profile.html', context)

def logout(request):
    '''Вместо этой функции можно в маршрутах просто прописать класс LogoutView.as_view()
       предварительно сделав импорь
       И в настройка LOGOUT_REDIRECT_URL = "/"'''
    auth.logout(request)
    return redirect('index')

class EmailVerificationView(TitleMixin, TemplateView):
    title = 'Store - Подтверждение электронной почты'
    template_name = 'user/email_verification.html'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = User.objects.get(email=kwargs['email'])
        email_verifications = EmailVerification.objects.filter(user=user, code=code)
        if email_verifications.exists() and not email_verifications.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super().get(request, *args, **kwargs)
        else:
            return redirect('index')

user/templates/user/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href={% static "vendor/css/auth.css" %}  rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">

    {% block content %}{% endblock content %}
        
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src={% static "vendor/js/auth-admin.js" %}></script>
</body>
</html>

user/templates/user/basket.html
{% if basket %}
<div class="col-lg-5">
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина <span class="badge badge-secondary badge-pill">{{ basket.total_quantity }}</span>
    </h4>
    {% for item in basket %}
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ item.product.name }}</h5>
            <p class="card-text">{{ item.product.discription }}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item bg-light">
                <div class="row text-center">
                    <div class="col-lg-4">
                        <input name="basketID" type="number" class="form-control"
                               value={{ item.quantity }}>
                    </div>
                    <div class="col-lg-4">{{ item.sum }} руб.</div>
                    <div class="col-lg-4">
                        <a href={% url 'products:basket_remove' item.id %}>
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    {% endfor %}
    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{ basket.total_sum }} руб.</h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right" href={% url 'orders:order_create' %}>
        Оформить заказ
    </a>
</div>
{% else %}
<h4 class="col-lg-5 mt-3  text-center">
    Корзина пуста
</h4>
{% endif %}

user/templates/user/email_verification.html
{% extends 'user/base.html' %}


{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Поздравляем</h3>
                    </div>
                    <div class="card-body text-center">
                        <h4>Ваша учетная запись успешно подтверждена!</h4>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small"><a href={% url 'user:login' %}>Продолжить</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

user/templates/user/login.html
{% extends 'user/base.html' %}
{% load socialaccount %}


{% block content %}
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        {% if messages or form.non_field_errors %}
                        <div class="alert 
                         {% if messages %} alert-success {% else %} alert-warning {% endif %} 
                         alert-dismissible fade show" role="alert" style="margin-top: 50px;">
                            {% if messages %}
                                {% for message in messages %}
                                    {{ message}}
                                {% endfor %}
                            {% else %}
                                <strong>{{ form.non_field_errors }}</strong> 
                            {% endif %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                            </div>
                            <div class="card-body">
                                <form action={% url 'user:login' %} method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label class="small mb-1" for='{{ form.username.id_for_lable }}'>
                                            Имя пользователя
                                        </label>
                                        {{ form.username }}
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for={{ form.password.id_for_lable }}>Пароль</label>
                                        {{ form.password }}
                                    </div> 
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="#">Забыли пароль?</a>
                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a href="#">
                                            <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i>
                                        </a>
                                        <a href={% provider_login_url 'github' next="/" %}>
                                            <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-facebook fa-2x" style="color: #405794;"></i>
                                        </a>
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href={% url 'user:register' %}>Нужен аккаунт? Зарегистрируйся!</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock content %}

user/templates/user/profile.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
<link href={% static "vendor/css/profile.css" %} rel="stylesheet">
{% endblock css %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Профиль</h4>
            <div class="col-lg-12 text-center">
                <img width="100" height="100"
                     src={% if user.image %} {{ user.image.url }} {% else %} {% static 'vendor/img/users/default_avatar.jpg' %}{% endif %}
                     class="img-thumbnail">
            </div>
            <form action="{% url 'user:profile' user.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for={{ form.first_name.id_for_label}}>Имя</label>
                            {{ form.first_name}}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for={{ form.last_name.id_for_label}}>Фамилия</label>
                            {{form.last_name}}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{ form.image }}
                            <label class="custom-file-label" for={{ form.image.id_for_label }}>Выберите изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for={{ form.username.id_for_label}}>Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for={{ form.email.id_for_label }}>Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
        {% include 'user/basket.html' %}
    </div>
</div>
{% endblock content %}

user/templates/user/register.html
{% extends 'user/base.html' %}


{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                {% if form.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert"
                    style="margin-top: 50px;">
                    {{ form.errors}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                    </div>
                    <div class="card-body">
                        <form action={% url 'user:register' %} method='post'>
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for={{ form.first_name.id_for_label }}>Имя</label>
                                        {{ form.first_name }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for={{ form.last_name.id_for_label }}>Фамилия</label>
                                        {{ form.last_name }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-6">
                                    <label class="small mb-1" for={{ form.username.id_for_label }}>Имя пользователя</label>
                                    {{ form.username }}
                                </div>
                                <div class="col-md-6">
                                    <label class="small mb-1" for={{ form.email.id_for_label }}>Адрес электронной
                                        почты</label>
                                        {{ form.email }}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for={{ form.password1.id_for_label }}>Пароль</label>
                                        {{ form.password1 }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for={{ form.password2.id_for_label }}>Подтверждение
                                            пароля</label>
                                            {{ form.password2 }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mt-4 mb-0">
                                <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small"><a href={% url 'user:login' %}>Уже есть аккаунт? Авторизоваться</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}


    