api/urls.py
from .views import *                                
from django.urls import path, include
# from django.views.decorators.cache import cache_page
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'products', ProductsViewSet)
router.register(r'basket', BasketViewSet)

app_name= 'api'
urlpatterns = [
    path('', include(router.urls)),
    path('', include(router.urls)),
]

main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from products.views import *
from django.conf.urls.static import static
from orders.views import stripe_webhook_view
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('user/', include('user.urls', namespace='user')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', views.obtain_auth_token)
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from .views import *                                
from django.urls import path


app_name= 'orders'

urlpatterns = [
    path('order_create/', OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('order_success/', SuccessOrderView.as_view(), name='order_success'),
    path('order_cancel/', CanceledOrderView.as_view(), name='order_cancel'),
    path('', OrderListView.as_view(), name='order_list'),
]

products/urls.py
from .views import *                                
from django.urls import path
# from django.views.decorators.cache import cache_page

app_name= 'products'
urlpatterns = [
    # path('', cache_page(15)(ProductsListView.as_view()), name='index'),
    path('', ProductsListView.as_view(), name='index'),
    # контроллер будет тот же, просто в него добавим условие проверки
    path('category/<int:category_id>', ProductsListView.as_view(), name='category'),
    # #
    path('page/<int:page>', ProductsListView.as_view(), name='paginator'),
    # int прописывается так же как и в контроллеле параметр функции и в шаблоне его передаем 
    path('basket/add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required

app_name = 'user'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserCreateView.as_view(), name='register'),
    # UpdateView должен получить в маршруте pk пользователя с которым работает!!! 
    path('profile/<int:pk>', ProfileUpdateView.as_view(), name='profile'),
    path('logout/', logout, name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
]

products/models.py
from user.models import User
from django.db import models
import stripe
from django.conf import settings
import logging

logger = logging.getLogger('main')
stripe.api_key = settings.STRIPE_SECRET_KEY 


class ProductsCategory(models.Model):
    namme = models.CharField(max_length=150, unique=True)
    discription = models.TextField(null=True, blank=True)

    def __str__(self): 
        return self.namme

    class Meta:
        # Это в админке буду названия адекватные
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ['id']

class Products(models.Model):
    name = models.CharField(max_length=255)
    # Поле не обязательное для заполнения, если пустые скобки
    discription = models.TextField() 
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images', blank=True)
    category = models.ForeignKey('ProductsCategory', on_delete=models.CASCADE)
    strip_id = models.CharField(max_length=128, blank=True)

    def __str__(self): 
        return f'Продукт: {self.name} | Категория: {self.category.namme}'

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ['id']

    def save(self, force_insert=False , force_update=False, using= None, update_fields=None):
        if not self.strip_id:
            stripe_product_price = self.create_stripe_price()
            self.strip_id = stripe_product_price['id']
        return super().save(force_insert, force_update, using, update_fields)

    def create_stripe_price(self):
        '''Эти строки из документации API strip'''
        stripe_product = stripe.Product.create(name=self.name)
        stripe_price = stripe.Price.create(
            product=stripe_product['id'],
            unit_amount=round(self.price * 100),
            currency='rub',
        )
        return stripe_price

class BasketQuerySet(models.QuerySet):
    '''Создали нужные нам методы, которые имеют доступ в шаблоне,
       к списку переданному через контекст, вне цикла'''
    # Как бы расширили менеджер объектов objects #
    def total_sum(self):
        return sum(item.sum() for item in self)

    def total_quantity(self):
        return sum(item.quantity for item in self)


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    # Добавляется время после создания, автоматически
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def sum(self):
        return self.product.price * self.quantity

    def __str__(self) -> str:
        return f'Корзина для {self.user.email} | Продукт: {self.product.name}'

    def de_json(self):
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum())
        }
        return basket_item

    @classmethod
    def create_or_update(cls, product_id, user):
        '''Basket.create_or_update > OK!'''
        basket_item = Basket.objects.filter(user=user, product_id=product_id)
        if not basket_item.exists():
            obj = Basket.objects.create(user=user, product_id=product_id, quantity=1)
            is_created = True
            return obj, is_created
        else:
            is_created = False
            basket = basket_item.first()
            basket.quantity += 1
            basket.save()
            return basket, is_created

products/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
# from django.core.paginator import Paginator
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from common.utils import TitleMixin
from django.core.cache import cache
from products.models import *
import logging

logger = logging.getLogger('main')
# Всегда в конце ставить View, для других разработчиков
class IndexView(TitleMixin, TemplateView):
    template_name = 'products/index.html'
    title = 'Store'

# def index(request):
#     context = {
#         'title': 'Главная страница'
#     }
#     return render(request, 'products/index.html', context)

class ProductsListView(TitleMixin, ListView):
    model = Products   # По умолчания выбирает все записи из БД
    template_name = "products/products.html"
    context_object_name = 'products'  # Стандарное имя object_list
    paginate_by = 6
    title = 'Store - Каталог'

    def get_context_data(self, **kwargs):
        ''' For traning cached categories'''        
        context = super().get_context_data(**kwargs)
        categories = cache.get('categories')   
        # cache categories
        if not categories:
            context["categories"] = ProductsCategory.objects.all()
            cache.set('categories', context["categories"], 15) 
        else:
            context["categories"] = categories
        return context
    
    def get_queryset(self): # Изначально этот метод выбирает все записи 
        queryset = super().get_queryset()
        # Это все что передается в url как параметр, slag или int/ хранится в self.kwargs
        category_id = self.kwargs.get('category_id')  # Метод get не возвратит ошибку, если придет None
        return queryset.filter(category__pk=category_id) if category_id else queryset
    
    
# def products(request, category_id=None, page_number=1): # Это значит не всегда передается второй агрумент
  
#     if category_id:
#         # Мой эксперементальный запрос  и он верный, выбираем сначала
#         # поле, которое форейн ки, и потом поле в соединенной таблице
#         products = Products.objects.filter(category__pk=category_id)
#     else:
#         products = Products.objects.all()

#     per_page = 1 # Количество товаров на странице
#     paginator = Paginator(products, per_page)
#     products_paginator = paginator.page(page_number)
#     context = {
#     'title': 'Store',
#     'categories': ProductsCategory.objects.all(),
#     'products': products_paginator,
#     }
        
#     return render(request, 'products/products.html', context)
    

@login_required()
def basket_add(request, product_id):
    Basket.create_or_update(product_id, request.user)
    logger.info('An item has added in basket')
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

@login_required()
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    logger.warning('delete from basket')
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

products/templates/products/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href={% static "vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    {% block css %}{% endblock css %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href={% url 'index' %}>Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-link">Привет! {{ user.first_name }}</li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href={% url 'products:index' %}>Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href={% url 'user:profile' user.id %}>Профиль</a>
                        </li>
                        <li><a class="dropdown-item" href={% url 'orders:order_list' %}>Заказы</a></li>
                        {% if user.is_superuser or user.is_staff %}
                            <li><a class="dropdown-item" href={% url 'admin:index' %}>Админ-панель</a></li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href={% url 'user:logout' %}>
                                Выйти
                            </a>
                        </li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href={% url 'user:login' %}>Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                {% endif %}
                </ul>
        </div>
    </div>
</nav>

{% block content %}{% endblock content %}

{% block footer %}{% endblock footer %}


<!-- Bootstrap core JavaScript -->
<script src={% static "vendor/jquery/jquery.min.js" %}></script>
<script src={% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src={% static "vendor/fontawesome/fontawesome-icons.js" %} crossorigin="anonymous"></script>

</body>

</html>

products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}


{% block css %}
<link href={% static "vendor/css/index.css" %} rel="stylesheet">
{% endblock css %}


{% block content %}
<section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Store</h1>
                <p>
                    Новые образы и лучшие бренды на Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href={% url 'products:index' %}>
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
 </section>
{% endblock content %}

products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}



{% block css %}
<link href={% static "vendor/css/products.css" %} rel="stylesheet">
{% endblock css %}


{% block content %}
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            <div class="list-group">
                {% for category in categories %}
                <a href={% url 'products:category' category.id %} class="list-group-item">{{ category.namme }}</a>
                {% endfor %}
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src='{% static "vendor/img/slides/slide-1.jpg" %}' alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src='{% static "vendor/img/slides/slide-2.jpg" %}' alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src='{% static "vendor/img/slides/slide-3.jpg" %}' alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <!-- Кэш на уровне шаблона, пересекается с другими запросами/ отключил-->
    
            <div class="row">
                {% for item in products %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src='{{ item.image.url }}'
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">'{{ item.name }}'</a>
                            </h4>
                            <h5>{{ item.price }} руб.</h5>
                            <p class="card-text">{{ item.discription }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-success" href="{% url 'products:basket_add' item.id %}">
                                Отправить в корзину
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
     
            </div>
            <!--  Проверка, что вообще появится эта пагинация, а то может и не нужно -->
            {% if page_obj.has_other_pages %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <!-- Проверка, нужна ли стрелочка влево -->
                    {% if page_obj.has_previous %}
                        <li class="page-item disabled">
                            <a class="page-link" href={% url 'products:paginator' page_obj.previous_page_number %} tabindex="-1" aria-disabled="true">&lt;</a>
                        </li>
                    {% endif %}
                    {% for page in page_obj.paginator.page_range %}
                        {% if page_obj.number == page %}
                        <!--Указывает что ссылка активная-->
                        <li class="page-item active"><a class="page-link">{{ page }}</a></li>
                        <!--Условие при котором выводятся только соседние два номера пагинации слева и справва-->
                        {% elif page >= page_obj.number|add:-2 and page <= page_obj.number|add:2  %}
                        <li class="page-item"><a class="page-link" href={% url 'products:paginator' page %}>{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}
                    <!-- Проверка, нужна ли стрелочка вправо -->
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href={% url 'products:paginator' page_obj.next_page_number %}>&gt;</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>

    </div>

 </div>
{% endblock content %}


{% block footer %}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store 2022</p>
    </div>
    <!-- /.container -->
 </footer>
{% endblock footer %}